# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.CharField(max_length=140),
        ),
    ]
