# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20160917_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to=settings.AUTH_USER_MODEL),
        ),
    ]
